### PR TITLE
Updated README.md

### LINKED ISSUE #1: [Feature 1] Friend management system
Tina wants to add and remove other users as friends so she can quickly compare schedules with her friends and friend groups. She also wants to star friends to find them more quickly on her friends list.

### PR DESCRIPTION
**Pull request by thk421**
Updated the README file

### CODE REVIEW

**Review by clarencechau — COMMENTED** [review]
NICE

**Review by jeffhcs — DISMISSED** [review]
so COOOL tina

**Review by seajunk — DISMISSED** [review]
!!

**Review by naraeleee — DISMISSED** [review]
so cool

**Review by clarencechau — DISMISSED** [review]

**Pull request closed without merging**
